basePath: /v1
consumes:
- application/json
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      captcha_token:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - captcha_token
    - email
    - name
    - password
    type: object
  categories.CategoryDTO:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
      slug:
        type: string
      subcategories:
        description: To make Swagger not dig too deep
        items:
          type: object
        type: array
      updated_at:
        type: string
    type: object
  categories.PostCategoryBody:
    properties:
      name:
        maxLength: 200
        minLength: 2
        type: string
      parent_id:
        type: integer
    required:
    - name
    type: object
  categories.PutCategoryBody:
    properties:
      name:
        maxLength: 200
        minLength: 2
        type: string
      parent_id:
        type: integer
    required:
    - name
    type: object
  shared.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  shared.MessageResponse:
    properties:
      message:
        type: string
    type: object
  users.GetMeResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      oauth_type:
        type: string
      roles:
        items:
          type: string
        type: array
      verified:
        type: boolean
    type: object
info:
  contact:
    email: hello@luny.dev
    name: Nguyệt Ánh
  description: Backend API for CherryAuctions at cherry-auctions.luny.dev.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Cherry Auctions API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logins to an account using a username and a password registered
        with the server.
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad username or password format
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "401":
          description: Wrong password
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "404":
          description: Account does not exist
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "421":
          description: Account uses oauth but tries to login with password
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Server couldn't complete the request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Logins to an existing account
      tags:
      - authentication
  /auth/logout:
    post:
      description: Logouts, and also invalidates the refresh token. This does not
        revoke access tokens.
      responses:
        "204":
          description: Any request, regardless of authentication status
          schema:
            $ref: '#/definitions/shared.MessageResponse'
      summary: Logouts and invalidates the refresh token if available.
      tags:
      - authentication
  /auth/refresh:
    post:
      description: Uses the provided refresh token cookie to refresh on another short-lived
        access token.
      responses:
        "200":
          description: Refreshed successfully
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "204":
          description: Any request, regardless of authentication status
          schema:
            $ref: '#/definitions/shared.MessageResponse'
        "401":
          description: Did not attach refresh token
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Refreshs a JWT key pair.
      tags:
      - authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new account with the system using a email-password
        pair.
      parameters:
      - description: Register credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User was successfully registered
          schema:
            $ref: '#/definitions/shared.MessageResponse'
        "400":
          description: Request body is invalid
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "403":
          description: Captcha failed
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "409":
          description: An account with that email already exists
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: The request could not be completed due to server faults
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Registers a new account
      tags:
      - authentication
  /categories:
    get:
      description: This endpoint retrieves all categories in a fully recursive nested
        list, for easily displaying on the frontend.
      produces:
      - application/json
      responses:
        "200":
          description: List was successfully fetched
          schema:
            items:
              $ref: '#/definitions/categories.CategoryDTO'
            type: array
        "500":
          description: The request could not be completed due to server faults
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Retrieves a recursively nested list of categories.
      tags:
      - categories
    post:
      consumes:
      - application/json
      parameters:
      - description: New category data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/categories.PostCategoryBody'
      produces:
      - application/json
      responses:
        "201":
          description: Category was successfully created
          schema:
            $ref: '#/definitions/categories.CategoryDTO'
        "400":
          description: Category body data was invalid
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "403":
          description: Not enough permissions
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: The server could not complete the request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Creates a category
      tags:
      - categories
  /categories/{id}:
    delete:
      description: Soft-deletes a category record by setting a flag.
      parameters:
      - description: Category ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Category was deleted
        "400":
          description: Category body data was invalid
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "403":
          description: Not enough permissions
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "404":
          description: Category could not be found
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: The server could not complete the request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Soft-delete a category record
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category records by updating it partially
      parameters:
      - description: Category ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: New updated category data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/categories.PutCategoryBody'
      produces:
      - application/json
      responses:
        "200":
          description: Category was successfully changed, returns old category
          schema:
            $ref: '#/definitions/categories.CategoryDTO'
        "400":
          description: Category body data was invalid
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "403":
          description: Not enough permissions
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "404":
          description: Category could not be found
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: The server could not complete the request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update a category record
      tags:
      - categories
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Always
          schema:
            $ref: '#/definitions/shared.MessageResponse'
      summary: Checks health of the server.
      tags:
      - others
  /users/me:
    get:
      description: Retrieves information about your own profile if authenticated.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.GetMeResponse'
        "401":
          description: When unauthenticated
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "422":
          description: When your info had an invalid state on the server
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: The request could not be completed due to server faults
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Gets your own profile.
      tags:
      - users
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Classic Bearer token, authenticated by using the login endpoint,
      which should grant an access token. To refresh it, use the RefreshToken cookie.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
