name: CherryAuctions Backend CI/CD

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Don't truncate commit

      - uses: wagoid/commitlint-github-action@v6
        name: Commitlint

      - uses: actions/setup-go@v6
        name: Setup Go
        with:
          go-version-file: "./backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: backend

  test:
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit:latest
        ports:
          - 1025:1025
        env:
          MP_SMTP_AUTH_ACCEPT_ANY: "false"
          MP_SMTP_AUTH_USERS: "ciuser:cipass"
      rustfs:
        image: rustfs/rustfs:latest
        ports:
          - 9000:9000
        volumes:
          - rustfsdata:/data
        env:
          RUSTFS_ADDRESS: :9000
          RUSTFS_ACCESS_KEY: ciuser
          RUSTFS_SECRET_KEY: cipass
          RUSTFS_CONSOLE_ENABLE: false
    name: Test
    needs: ["lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        name: Setup Go
        with:
          go-version-file: "./backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - name: Test
        run: go test ./... -cover
        working-directory: backend
        env:
          SMTP_HOST: localhost
          SMTP_PORT: 1025
          SMTP_USER: ciuser
          SMTP_PASSWORD: cipass
          AWS_ACCESS_KEY_ID: ciuser
          AWS_SECRET_ACCESS_KEY: cipass
          AWS_S3_BASE: http://localhost:9000
          AWS_S3_USE_PATH_STYLE: true
          AWS_BUCKET_NAME: cherry-auctions
          GIN_MODE: release

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: ["test"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        name: Setup Go 1.25.4
        with:
          go-version-file: "./backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - name: Build
        working-directory: backend
        run: go build .

  docker:
    runs-on: ubuntu-latest
    name: Docker Build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (Production)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/hikawi/cherry-auctions:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: ["docker"]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency:
      group: "production"
      cancel-in-progress: false
    environment:
      name: Production
      url: https://status.luny.dev
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e 

            cd /srv
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose up -d --pull always cherry-auctions
            docker system prune -af

  # To be continued for when the project foundation, backend and frontend is setup.
