name: CherryAuctions Frontend CI/CD

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commit Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: wagoid/commitlint-github-action@v6
        name: Commitlint

  lint:
    runs-on: ubuntu-latest
    name: Code Lint
    needs: ["commitlint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install Node dependencies
        working-directory: frontend
        run: pnpm i --frozen-lockfile

      - name: Lint
        working-directory: frontend
        run: pnpm lint

  unittest:
    runs-on: ubuntu-latest
    name: Unit Testing
    needs: ["lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install Node dependencies
        working-directory: frontend
        run: pnpm i --frozen-lockfile

      - name: Unit Tests (Vitest)
        run: pnpm test:unit
        working-directory: frontend

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: ["e2etest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install Node dependencies
        working-directory: frontend
        run: pnpm i --frozen-lockfile

      - name: Build
        working-directory: frontend
        run: pnpm build
